### PR TITLE
Upstream rebased

### PR DESCRIPTION
**Pull request by S-S-X**
#11 But actually merge would probably be better option to get proper history and probably less conflicts cause by diverged tree.

### CODE REVIEW

**Comment by S-S-X** [comment]
```
    touchscreen.lua:335:1: inconsistent indentation (SPACE followed by TAB)
    touchscreen.lua:336:1: inconsistent indentation (SPACE followed by TAB)
    touchscreen.lua:342:12: line contains trailing whitespace
```

**Comment by OgelGames** [comment]
Also not sure about the advanced touchscreen, it's actually good that the touchscreen does the work of "building" the formspec from commands, it's less work (and less code) for the Luacontroller...

**Comment by S-S-X** [comment]
Let's see if merge seems okayish, if we do not merge upstream history soon rebases cannot be managed soon anymore. Created another branch for this.
For that deleting commits wont work (or I don't know how...) so I did revert for movestone recipe.

**Comment by S-S-X** [comment]
Also cherry picked "fix luacheck warnings and remove stray print()" there so I'll close this. Complete history will be so nice when merging next updates, not mess like it currently is...

**Pull request closed without merging**
